export const browserTabsMock: Partial<typeof browser.tabs> = {
  get: jest.fn(),
  getCurrent: jest.fn(),
  connect: jest.fn(),
  sendMessage: jest.fn(),
  create: jest.fn(),
  duplicate: jest.fn(),
  query: jest.fn(),
  highlight: jest.fn(),
  update: jest.fn(),
  move: jest.fn(),
  reload: jest.fn(),
  warmup: jest.fn(),
  remove: jest.fn(),
  discard: jest.fn(),
  detectLanguage: jest.fn(),
  toggleReaderMode: jest.fn(),
  captureTab: jest.fn(),
  captureVisibleTab: jest.fn(),
  executeScript: jest.fn(),
  insertCSS: jest.fn(),
  removeCSS: jest.fn(),
  setZoom: jest.fn(),
  getZoom: jest.fn(),
  setZoomSettings: jest.fn(),
  getZoomSettings: jest.fn(),
  print: jest.fn(),
  printPreview: jest.fn(),
  saveAsPDF: jest.fn(),
  show: jest.fn(),
  hide: jest.fn(),
  onActivated: {
    addListener: jest.fn()
  } as any
};
